spring.application.name=ticketing-system


spring.datasource.url=jdbc:mysql://localhost:3306/tickets
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

# Helpful for debugging via Postman (shows validation/exception messages)
server.error.include-message=always
server.error.include-binding-errors=always

jwt.secret=7f3e1c9a4d8b2f6e9c1a5b7d3e4f8a6c2d9b1f7e3a5c8d4b6f1e7a9c3d2b5f4e8c7a1d3f6b2e4c9a7f1d8b3e6c2f5a9d7e1c4b2f8
jwt.expiration=86400000
